[colors.bright]
black = "#32302f"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#f9f5d7"
yellow = "#fabf2f"

[colors.cursor]
cursor = "#3b4244"
text = "#d6d6d6"

[colors.normal]
black = "#0A0E14"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#f2e5bc"
yellow = "#b57614"

[colors.primary]
background = "#0A0E14"
foreground = "#B3B1AD"

[cursor]
thickness = 0.3

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 12.0

[font.normal]
family = "SpaceMono Nerd Font Mono"

[shell]
program = "/bin/bash"

[window]
decorations = "full"

[window.dimensions]
columns = 124
lines = 20

[window.padding]
x = 20
y = 20

[window.position]
x = 0
y = 0
