[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-continuation-of-dream-1920×1080
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-continuation-of-dream-1920×1080
GtkTheme=oomox-continuation-of-dream-1920×1080
IconTheme=oomox-continuation-of-dream-1920×1080
MetacityTheme=oomox-continuation-of-dream-1920×1080
